.PHONY: help agents macbook macbook-admin linux

# Default target shows help
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  agents        - Generate Pi's AGENTS.md from shared base + Pi overlay"
	@echo "  macbook       - Switch to macOS configuration"
	@echo "  macbook-admin - Switch to macOS configuration as administrator"
	@echo "  linux         - Switch to Linux (home-manager) configuration"

.DEFAULT_GOAL := help

# Generated agent-guidance sources (single source of truth) and output.
# OpenCode layers these natively via its `instructions` array; Pi has no
# include mechanism, so its global AGENTS.md is assembled here.
AGENTS_BASE := shared/config/agents/personal-base.md
AGENTS_PI_OVERLAY := shared/config/agents/overlays/pi.md
PI_AGENTS := shared/config/pi/AGENTS.md

# Assemble Pi's global AGENTS.md from the shared base plus the Pi overlay.
# Idempotent: re-running produces identical bytes (safe to commit).
agents:
	@printf '%s\n\n' '<!-- GENERATED by `make agents` from shared/config/agents/personal-base.md + shared/config/agents/overlays/pi.md. Do not edit this file directly. -->' > $(PI_AGENTS)
	@cat $(AGENTS_BASE) >> $(PI_AGENTS)
	@printf '\n' >> $(PI_AGENTS)
	@cat $(AGENTS_PI_OVERLAY) >> $(PI_AGENTS)
	@echo "Generated $(PI_AGENTS)"

# macOS system configuration
macbook: agents
	REPO_DIR=$(CURDIR) sudo -E nix run nix-darwin -- switch --flake .#macbook --impure

# macOS system configuration from administrator account
macbook-admin: agents
	rm -rf /tmp/macos-config
	sudo cp -r $(CURDIR) /tmp/macos-config
	REPO_DIR=$(CURDIR) sudo -E -H nix run nix-darwin -- switch --flake /tmp/macos-config#macbook-admin --impure

# Linux home-manager standalone configuration
linux: agents
	REPO_DIR=$(CURDIR) nix run home-manager -- switch --flake .#linux --impure
